apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-backend-lb
  name: api-backend-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: backend
  selector:
    app: api-backend
  type: LoadBalancer
