apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: database
  name: database
spec:
  serviceName: mysql-db-svc
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: {AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/database:1.0
        name: database
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret           
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE
