apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-db-svc
  name: mysql-db-svc
spec:
  clusterIP: None
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: database
